FROM python:3.10-slim

WORKDIR /app

COPY necessidades.txt .
RUN pip install --no-cache-dir -r necessidades.txt
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. jogotipo.proto

COPY grpc/servidor_grcp.py .
COPY grpc/jogotipo.proto .
COPY grpc/jogotipo_pb2.py .
COPY grpc/jogotipo_pb2_grpc.py .
COPY Jogos/jogos.xml ./jogos.xml

CMD ["python", "grpc.py"]